package com.example.android.youtubemusicplayer.download_music

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import androidx.lifecycle.ViewModel
import com.example.android.youtubemusicplayer.database.Song
import com.example.android.youtubemusicplayer.database.MusicDatabaseDao
import com.example.android.youtubemusicplayer.database.SongWithAlbumAndArtist

class DownloadMusicViewModel(val database: MusicDatabaseDao,
                             application: Application) : AndroidViewModel(application) {

    val songWithAlbumAndArtist : LiveData<List<SongWithAlbumAndArtist>> = database.getSongWithAlbumAndArtist();

    val downloadableSongsSelected = mutableListOf<DownloadableSong>();

    val downloadableSongs = arrayOf(
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Ariana Grande - Moonlight_sample.mp3", "Moonlight_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Daft Punk - Give Life Back to Music_sample.mp3", "Give Life Back to Music_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Eminem - Curtains Up (Skit)_sample.mp3", "Curtains Up (Skit)_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. John Lennon; The Plastic Ono Band - Power to the People_sample.mp3", "Power to the People_sample", "John Lennon; The Plastic Ono Band"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Led Zeppelin - Good Times Bad Times_sample.mp3", "Good Times Bad Times_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Luis Fonsi - Fight The Feeling_sample.mp3", "Fight The Feeling_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Michael Jackson - Wanna Be Startin' Somethin'_sample.mp3", "Wanna Be Startin' Somethin'_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Nirvana - Smells Like Teen Spirit_sample.mp3", "Smells Like Teen Spirit_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Pink Floyd - Speak to Me - Breathe_sample.mp3", "Breathe_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Queen - Procession_sample.mp3", "Procession_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Taylor Swift - Fearless_sample.mp3", "Fearless_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Taylor Swift - Tim McGraw_sample.mp3", "Tim McGraw_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. The Jimi Hendrix Experience - Purple Haze_sample.mp3", "Purple Haze_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01. Wisin & Yandel; Mr. Phillip - Dale (intro)_sample.mp3", "Dale (intro)_sample", "Wisin & Yandel; Mr. Phillip"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.01. The Rolling Stones - Street Fighting Man_sample.mp3", "Street Fighting Man_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.02. The Rolling Stones - Gimme Shelter_sample.mp3", "Gimme Shelter_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.03. The Rolling Stones - (I Can't Get No) Satisfaction_sample.mp3", "(I Can't Get No) Satisfaction_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.04. The Rolling Stones - The Last Time_sample.mp3", "The Last Time_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.05. The Rolling Stones - Jumpin' Jack Flash_sample.mp3", "Jumpin' Jack Flash_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.06. The Rolling Stones - You Can't Always Get What You Want_sample.mp3", "You Can't Always Get What You Want_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.07. The Rolling Stones - 19th Nervous Breakdown_sample.mp3", "19th Nervous Breakdown_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.08. The Rolling Stones - Under My Thumb_sample.mp3", "Under My Thumb_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.09. The Rolling Stones - Not Fade Away_sample.mp3", "Not Fade Away_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.10. The Rolling Stones - Have You Seen Your Mother Baby__sample.mp3", "Have You Seen Your Mother Baby__sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.11. The Rolling Stones - Sympathy for the Devil_sample.mp3", "Sympathy for the Devil_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.12. The Rolling Stones - Mother's Little Helper_sample.mp3", "Mother's Little Helper_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.13. The Rolling Stones - She's a Rainbow_sample.mp3", "She's a Rainbow_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.14. The Rolling Stones - Get Off of My Cloud_sample.mp3", "Get Off of My Cloud_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.15. The Rolling Stones - Wild Horses_sample.mp3", "Wild Horses_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.16. The Rolling Stones - Ruby Tuesday_sample.mp3", "Ruby Tuesday_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.17. The Rolling Stones - Paint It, Black_sample.mp3", "Paint It, Black_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.18. The Rolling Stones - Honky Tonk Women_sample.mp3", "Honky Tonk Women_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.19. The Rolling Stones - It's All Over Now_sample.mp3", "It's All Over Now_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/01.20. The Rolling Stones - Let's Spend the Night Together_sample.mp3", "Let's Spend the Night Together_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Ariana Grande - Dangerous Woman_sample.mp3", "Dangerous Woman_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Daft Punk - The Game of Love_sample.mp3", "The Game of Love_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Eminem - White America_sample.mp3", "White America_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. John Lennon; The Plastic Ono Band; The Flux Fiddlers - Jealous Guy_sample.mp3", "Jealous Guy_sample", "John Lennon; The Plastic Ono Band; The Flux Fiddlers"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Led Zeppelin - Babe I'm Gonna Leave You_sample.mp3", "Babe I'm Gonna Leave You_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Luis Fonsi - Secret_sample.mp3", "Secret_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Michael Jackson - Baby Be Mine_sample.mp3", "Baby Be Mine_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Nirvana - In Bloom_sample.mp3", "In Bloom_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Pink Floyd - On the Run_sample.mp3", "On the Run_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Queen - Father to Son_sample.mp3", "Father to Son_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Taylor Swift - Fifteen_sample.mp3", "Fifteen_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Taylor Swift - Picture to Burn_sample.mp3", "Picture to Burn_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. The Jimi Hendrix Experience - Fire_sample.mp3", "Fire_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02. Wisin & Yandel - Manigueta_sample.mp3", "Manigueta_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.01. The Rolling Stones - Start Me Up_sample.mp3", "Start Me Up_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.02. The Rolling Stones - Brown Sugar_sample.mp3", "Brown Sugar_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.03. The Rolling Stones - Miss You_sample.mp3", "Miss You_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.04. The Rolling Stones - Beast of Burden_sample.mp3", "Beast of Burden_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.05. The Rolling Stones - Don't Stop_sample.mp3", "Don't Stop_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.06. The Rolling Stones - Happy_sample.mp3", "Happy_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.07. The Rolling Stones - Angie_sample.mp3", "Angie_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.08. The Rolling Stones - You Got Me Rocking_sample.mp3", "You Got Me Rocking_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.09. The Rolling Stones - Shattered_sample.mp3", "Shattered_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.10. The Rolling Stones - Fool to Cry_sample.mp3", "Fool to Cry_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.11. The Rolling Stones - Love Is Strong_sample.mp3", "Love Is Strong_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.12. The Rolling Stones - Mixed Emotions_sample.mp3", "Mixed Emotions_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.13. The Rolling Stones - Keys to Your Love_sample.mp3", "Keys to Your Love_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.14. The Rolling Stones - Anybody Seen My Baby__sample.mp3", "Anybody Seen My Baby__sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.15. The Rolling Stones - Stealing My Heart_sample.mp3", "Stealing My Heart_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.16. The Rolling Stones - Tumbling Dice_sample.mp3", "Tumbling Dice_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.17. The Rolling Stones - Undercover of the Night_sample.mp3", "Undercover of the Night_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.18. The Rolling Stones - Emotional Rescue_sample.mp3", "Emotional Rescue_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.19. The Rolling Stones - It's Only Rock 'n' Roll_sample.mp3", "It's Only Rock 'n' Roll_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/02.20. The Rolling Stones - Losing My Touch_sample.mp3", "Losing My Touch_sample", "The Rolling Stones"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Ariana Grande - Be Alright_sample.mp3", "Be Alright_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Daft Punk - Giorgio by Moroder_sample.mp3", "Giorgio by Moroder_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Eminem - Business_sample.mp3", "Business_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. John Lennon; The Plastic Ono Band; Elephant's Memory; Invisible Strings - New York City_sample.mp3", "New York City_sample", "John Lennon; The Plastic Ono Band; Elephant's Memory; Invisible Strings"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Led Zeppelin - You Shook Me_sample.mp3", "You Shook Me_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Luis Fonsi - Turn It Up_sample.mp3", "Turn It Up_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Michael Jackson; Paul McCartney - The Girl Is Mine_sample.mp3", "The Girl Is Mine_sample", "Michael Jackson; Paul McCartney"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Nirvana - Come as You Are_sample.mp3", "Come as You Are_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Pink Floyd - Time_sample.mp3", "Time_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Queen - White Queen (As It Began)_sample.mp3", "White Queen (As It Began)_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Taylor Swift - Love Story_sample.mp3", "Love Story_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Taylor Swift - Teardrops on My Guitar_sample.mp3", "Teardrops on My Guitar_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. The Jimi Hendrix Experience - The Wind Cries Mary_sample.mp3", "The Wind Cries Mary_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/03. Wisin & Yandel - Llamé pa' verte (Bailando sexy)_sample.mp3", "Llamé pa' verte (Bailando sexy)_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Ariana Grande - Into You_sample.mp3", "Into You_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Daft Punk - Within_sample.mp3", "Within_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Eminem - Cleanin Out My Closet_sample.mp3", "Cleanin Out My Closet_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. John Lennon; The Plastic Ono Band - Mind Games_sample.mp3", "Mind Games_sample", "John Lennon; The Plastic Ono Band"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Led Zeppelin - Dazed and Confused_sample.mp3", "Dazed and Confused_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Luis Fonsi - Save Me_sample.mp3", "Save Me_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Michael Jackson - Thriller_sample.mp3", "Thriller_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Nirvana - Breed_sample.mp3", "Breed_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Pink Floyd - The Great Gig in the Sky_sample.mp3", "The Great Gig in the Sky_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Queen - Some Day One Day_sample.mp3", "Some Day One Day_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Taylor Swift - A Place in This World_sample.mp3", "A Place in This World_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Taylor Swift - Hey Stephen_sample.mp3", "Hey Stephen_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. The Jimi Hendrix Experience - Hey Joe_sample.mp3", "Hey Joe_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/04. Wisin & Yandel; Daddy Yankee - Paleta (Feat. Daddy Yankee)_sample.mp3", "Paleta (Feat. Daddy Yankee)_sample", "Wisin & Yandel; Daddy Yankee"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Ariana Grande Feat. Nicki Minaj - Side To Side_sample.mp3", "Side To Side_sample", "Ariana Grande Feat. Nicki Minaj"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Daft Punk - Instant Crush_sample.mp3", "Instant Crush_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Eminem - Square Dance_sample.mp3", "Square Dance_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. John Lennon; The Plastic Ono Band - Bless You_sample.mp3", "Bless You_sample", "John Lennon; The Plastic Ono Band"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Led Zeppelin - Your Time Is Gonna Come_sample.mp3", "Your Time Is Gonna Come_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Luis Fonsi - You Got Nothing On Me_sample.mp3", "You Got Nothing On Me_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Michael Jackson - Beat It_sample.mp3", "Beat It_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Nirvana - Lithium_sample.mp3", "Lithium_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Pink Floyd - Money_sample.mp3", "Money_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Queen - The Loser in the End_sample.mp3", "The Loser in the End_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Taylor Swift - Cold as You_sample.mp3", "Cold as You_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Taylor Swift - White Horse_sample.mp3", "White Horse_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. The Jimi Hendrix Experience - All Along the Watchtower_sample.mp3", "All Along the Watchtower_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/05. Wisin & Yandel - Solo Una Noche_sample.mp3", "Solo Una Noche_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Ariana Grande Feat. Lil Wayne - Let Me Love You_sample.mp3", "Let Me Love You_sample", "Ariana Grande Feat. Lil Wayne"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Daft Punk - Lose Yourself to Dance_sample.mp3", "Lose Yourself to Dance_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Eminem - The Kiss (Skit)_sample.mp3", "The Kiss (Skit)_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. John Lennon - Slippin' and Slidin'_sample.mp3", "Slippin' and Slidin'_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Led Zeppelin - Black Mountain Side_sample.mp3", "Black Mountain Side_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Luis Fonsi - If Only_sample.mp3", "If Only_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Michael Jackson - Billie Jean_sample.mp3", "Billie Jean_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Nirvana - Polly_sample.mp3", "Polly_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Pink Floyd - Us and Them_sample.mp3", "Us and Them_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Queen - Ogre Battle_sample.mp3", "Ogre Battle_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Taylor Swift - The Outside_sample.mp3", "The Outside_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Taylor Swift - You Belong With Me_sample.mp3", "You Belong With Me_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. The Jimi Hendrix Experience - Stone Free_sample.mp3", "Stone Free_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/06. Wisin & Yandel - Mayor Que Yo, Parte 2_sample.mp3", "Mayor Que Yo, Parte 2_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Ariana Grande - Greedy_sample.mp3", "Greedy_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Daft Punk - Touch_sample.mp3", "Touch_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Eminem - Soldier_sample.mp3", "Soldier_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. John Lennon - Here We Go Again_sample.mp3", "Here We Go Again_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Led Zeppelin - Communication Breakdown_sample.mp3", "Communication Breakdown_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Luis Fonsi - Keep My Cool_sample.mp3", "Keep My Cool_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Michael Jackson - Human Nature_sample.mp3", "Human Nature_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Nirvana - Territorial Pissings_sample.mp3", "Territorial Pissings_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Pink Floyd - Any Colour You Like_sample.mp3", "Any Colour You Like_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Queen - The Fairy Feller's Master‐Stroke_sample.mp3", "The Fairy Feller's Master‐Stroke_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Taylor Swift - Tied Together With a Smile_sample.mp3", "Tied Together With a Smile_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Taylor Swift; Colbie Caillat - Breathe_sample.mp3", "Breathe_sample", "Taylor Swift; Colbie Caillat"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. The Jimi Hendrix Experience - Crosstown Traffic_sample.mp3", "Crosstown Traffic_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/07. Wisin & Yandel; Héctor _El Father_ - La barriá_sample.mp3", "La barriá_sample", "Wisin & Yandel; Héctor _El Father_"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Ariana Grande Feat. Macy Gray - Leave Me Lonely_sample.mp3", "Leave Me Lonely_sample", "Ariana Grande Feat. Macy Gray"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Daft Punk - Get Lucky_sample.mp3", "Get Lucky_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Eminem - Say Goodbye Hollywood_sample.mp3", "Say Goodbye Hollywood_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. John Lennon - Beautiful Boy (Darling Boy)_sample.mp3", "Beautiful Boy (Darling Boy)_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Led Zeppelin - I Can't Quit You Baby_sample.mp3", "I Can't Quit You Baby_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Luis Fonsi - Tell Her Tonight_sample.mp3", "Tell Her Tonight_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Michael Jackson - P.Y.T. (Pretty Young Thing)_sample.mp3", "P.Y.T. (Pretty Young Thing)_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Nirvana - Drain You_sample.mp3", "Drain You_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Pink Floyd - Brain Damage_sample.mp3", "Brain Damage_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Queen - Nevermore_sample.mp3", "Nevermore_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Taylor Swift - Stay Beautiful_sample.mp3", "Stay Beautiful_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Taylor Swift - Tell Me Why_sample.mp3", "Tell Me Why_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. The Jimi Hendrix Experience - Manic Depression_sample.mp3", "Manic Depression_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/08. Wisin & Yandel - Calle Callejero_sample.mp3", "Calle Callejero_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Ariana Grande Feat. Future - Everyday_sample.mp3", "Everyday_sample", "Ariana Grande Feat. Future"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Daft Punk - Beyond_sample.mp3", "Beyond_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Eminem - Drips_sample.mp3", "Drips_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. John Lennon - Nobody Told Me_sample.mp3", "Nobody Told Me_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Led Zeppelin - How Many More Times_sample.mp3", "How Many More Times_sample", "Led Zeppelin"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Luis Fonsi - Twisted_sample.mp3", "Twisted_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Michael Jackson - The Lady in My Life_sample.mp3", "The Lady in My Life_sample", "Michael Jackson"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Nirvana - Lounge Act_sample.mp3", "Lounge Act_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Pink Floyd - Eclipse_sample.mp3", "Eclipse_sample", "Pink Floyd"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Queen - The March of the Black Queen_sample.mp3", "The March of the Black Queen_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Taylor Swift - Should've Said No_sample.mp3", "Should've Said No_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Taylor Swift - You're Not Sorry_sample.mp3", "You're Not Sorry_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. The Jimi Hendrix Experience - Little Wing_sample.mp3", "Little Wing_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/09. Wisin & Yandel - Sin él_sample.mp3", "Sin él_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Ariana Grande - Sometimes_sample.mp3", "Sometimes_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Daft Punk - Motherboard_sample.mp3", "Motherboard_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Eminem - Without Me_sample.mp3", "Without Me_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. John Lennon - Imagine (take 1)_sample.mp3", "Imagine (take 1)_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Luis Fonsi - One Night Thing_sample.mp3", "One Night Thing_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Nirvana - Stay Away_sample.mp3", "Stay Away_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Queen - Funny How Love Is_sample.mp3", "Funny How Love Is_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Taylor Swift - Mary's Song (Oh My My My)_sample.mp3", "Mary's Song (Oh My My My)_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Taylor Swift - The Way I Loved You_sample.mp3", "The Way I Loved You_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. The Jimi Hendrix Experience - If 6 Was 9_sample.mp3", "If 6 Was 9_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/10. Wisin & Yandel - Rakata_sample.mp3", "Rakata_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Ariana Grande - I Don't Care_sample.mp3", "I Don't Care_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Daft Punk - Fragments of Time_sample.mp3", "Fragments of Time_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Eminem - Paul Rosenberg (Skit)_sample.mp3", "Paul Rosenberg (Skit)_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Luis Fonsi - I Wish_sample.mp3", "I Wish_sample", "Luis Fonsi"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Nirvana - On a Plain_sample.mp3", "On a Plain_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Queen - Seven Seas of Rhye_sample.mp3", "Seven Seas of Rhye_sample", "Queen"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Taylor Swift - Forever & Always_sample.mp3", "Forever & Always_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Taylor Swift - Our Song_sample.mp3", "Our Song_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. The Jimi Hendrix Experience - Foxy Lady_sample.mp3", "Foxy Lady_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. The Plastic Ono Band - Give Peace a Chance_sample.mp3", "Give Peace a Chance_sample", "The Plastic Ono Band"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/11. Wisin & Yandel; Tony Dize - Sensación_sample.mp3", "Sensación_sample", "Wisin & Yandel; Tony Dize"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Ariana Grande - Bad Decisions_sample.mp3", "Bad Decisions_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Daft Punk - Doin' It Right_sample.mp3", "Doin' It Right_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Eminem - Sing For The Moment_sample.mp3", "Sing For The Moment_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. John Lennon - Grow Old With Me_sample.mp3", "Grow Old With Me_sample", "John Lennon"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Nirvana - Something in the Way - Endless, Nameless_sample.mp3", "Endless, Nameless_sample", "Nirvana"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Taylor Swift - The Best Day_sample.mp3", "The Best Day_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. The Jimi Hendrix Experience - Bold as Love_sample.mp3", "Bold as Love_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/12. Wisin & Yandel - Tabla_sample.mp3", "Tabla_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. Ariana Grande - Touch It_sample.mp3", "Touch It_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. Daft Punk - Contact_sample.mp3", "Contact_sample", "Daft Punk"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. Eminem - Superman_sample.mp3", "Superman_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. Taylor Swift - Change_sample.mp3", "Change_sample", "Taylor Swift"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. The Jimi Hendrix Experience - Castles Made of Sand_sample.mp3", "Castles Made of Sand_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/13. Wisin & Yandel; Aventura - Noche de sexo_sample.mp3", "Noche de sexo_sample", "Wisin & Yandel; Aventura"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/14. Ariana Grande - Knew Better - Forever Boy_sample.mp3", "Forever Boy_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/14. Eminem - Hailie's Song_sample.mp3", "Hailie's Song_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/14. The Jimi Hendrix Experience - Red House_sample.mp3", "Red House_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/14. Wisin & Yandel - Mírala bien_sample.mp3", "Mírala bien_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/15. Ariana Grande - Thinking Bout You_sample.mp3", "Thinking Bout You_sample", "Ariana Grande"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/15. Eminem - Steve Berman (Skit)_sample.mp3", "Steve Berman (Skit)_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/15. The Jimi Hendrix Experience - Voodoo Child (slight return)_sample.mp3", "Voodoo Child (slight return)_sample", "The Jimi Hendrix Experience"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/15. Wisin & Yandel - La compañía_sample.mp3", "La compañía_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/16. Eminem - When the Music Stops_sample.mp3", "When the Music Stops_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/16. Jimi Hendrix - Freedom_sample.mp3", "Freedom_sample", "Jimi Hendrix"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/16. Wisin & Yandel - Lento_sample.mp3", "Lento_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/17. Eminem - Say What You Say_sample.mp3", "Say What You Say_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/17. Jimi Hendrix - Night Bird Flying_sample.mp3", "Night Bird Flying_sample", "Jimi Hendrix"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/17. Wisin & Yandel - Títere_sample.mp3", "Títere_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/18. Eminem - 'Till I Collapse_sample.mp3", "'Till I Collapse_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/18. Jimi Hendrix - Angel_sample.mp3", "Angel_sample", "Jimi Hendrix"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/18. Wisin & Yandel - Yo quiero_sample.mp3", "Yo quiero_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/19. Eminem - My Dad's Gone Crazy_sample.mp3", "My Dad's Gone Crazy_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/19. Jimi Hendrix - Dolly Dagger_sample.mp3", "Dolly Dagger_sample", "Jimi Hendrix"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/19. Wisin & Yandel - Fuera de base_sample.mp3", "Fuera de base_sample", "Wisin & Yandel"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/20. Eminem - Curtains Close (Skit)_sample.mp3", "Curtains Close (Skit)_sample", "Eminem"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/20. Jimi Hendrix - Star Spangled Banner_sample.mp3", "Star Spangled Banner_sample", "Jimi Hendrix"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/20. Wisin & Yandel; Ja Rule - Rakata (remix)_sample.mp3", "Rakata (remix)_sample", "Wisin & Yandel; Ja Rule"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/21. Wisin & Yandel; Tea Time - Rakata (hip hop remix)_sample.mp3", "Rakata (hip hop remix)_sample", "Wisin & Yandel; Tea Time"),
        DownloadableSong("gs://musicplayer-2d048.appspot.com/22. Wisin & Yandel - Llamé pa' verte (bailando sexy) (instrumental)_sample.mp3", "Llamé pa' verte (bailando sexy) (instrumental)_sample", "Wisin & Yandel"),
        );
}